import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../app/globals.css";
import Footer from '@/components/footer/footer'
import Header from '@/components/header/header'
import Chatbot from '@/components/chatbot/chatbot'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Chatbot />
        <Footer />
      </body>
    </html>
  );
}
